/** Classes added to HTML generated by  By default classnames follow the BEM notation. */
export interface ClassNames {
  /** @default 'choices' */
  containerOuter: string;
  /** @default 'choicsq__inner' */
  containerInner: string;
  /** @default 'choicsq__input' */
  input: string;
  /** @default 'choicsq__input--cloned' */
  inputCloned: string;
  /** @default 'choicsq__list' */
  list: string;
  /** @default 'choicsq__list--multiple' */
  listItems: string;
  /** @default 'choicsq__list--single' */
  listSingle: string;
  /** @default 'choicsq__list--dropdown' */
  listDropdown: string;
  /** @default 'choicsq__item' */
  item: string;
  /** @default 'choicsq__item--selectable' */
  itemSelectable: string;
  /** @default 'choicsq__item--disabled' */
  itemDisabled: string;
  /** @default 'choicsq__item--choice' */
  itemChoice: string;
  /** @default 'choicsq__placeholder' */
  placeholder: string;
  /** @default 'choicsq__group' */
  group: string;
  /** @default 'choicsq__heading' */
  groupHeading: string;
  /** @default 'choicsq__button' */
  button: string;
  /** @default 'is-active' */
  activeState: string;
  /** @default 'is-focused' */
  focusState: string;
  /** @default 'is-open' */
  openState: string;
  /** @default 'is-disabled' */
  disabledState: string;
  /** @default 'is-highlighted' */
  highlightedState: string;
  /** @default 'is-selected' */
  selectedState: string;
  /** @default 'is-flipped' */
  flippedState: string;
  /** @default 'is-loading' */
  loadingState: string;
  /** @default 'has-no-results' */
  noResults: string;
  /** @default 'has-no-choices' */
  noChoices: string;
}
